
-- References
local _format, _concat, _rep = string.format, table.concat, string.rep

-- Parser functions
local parser = require('maker.cparse')

-- Head template
local HEAD = [[
/* This code is automatically generated by so/\/ata.
 
         "%s" Lua library.
%s
*/

#include <lua.h>
#include <lauxlib.h>

/* main C library */
#include "%s" 
]]

-- Tale template
local TALE = [[
// Constructor
int luaopen_%s (lua_State* L)
{
  luaL_newlib(L, %s);
  return 1;
}]]


-- Auxiliry methods
local aux = {}

-- Make array element
local function _arr2str (arr)
  local res = ""
  for i = 1, #arr do res = _format("%s[%d]", res, arr[i]) end
  return res
end

-- Make result variable name.
local function _fnResult (v) return v.var_name.."_res" end

-- Make whitespaces for shift.
local function _shift (n) return _rep(" ", 2*n) end

-- Make generated function name.
local function _cAuxName (info, dir)
  local nm = string.gsub(info.C, '( )', '_')
  local ret = 'void'
  nm = _format('l_%s_%s', dir, nm)
  if #info.arr_size > 0 then
    nm = _format("%s_%s", nm, _concat(info.arr_size, "_"))
  end
  if info.ptr_count > 0 then
    nm = _format("%s_%str", nm, _rep("p", info.ptr_count))
  end
  -- arguments
  local args = {"lua_State* L"}
  local aname = {"L"}
  local tp, size = info.C, ""
  if string.find(tp, "struct") and #info.arr_size == 0 and info.ptr_count == 0 then
    tp = tp.."*" 
  end
  if info.ptr_count > 0 then 
    tp = tp.._rep("*", info.ptr_count + (dir == "to" and 1 or 0)) 
  end
  if #info.arr_size > 0 then size = _arr2str(info.arr_size) end
  if dir == 'to' then
    aname[#aname+1] = "idx"
    args[#args+1] = "int "..aname[#aname]
    aname[#aname+1] = "dst"
    args[#args+1] = _format("%s %s%s", tp, aname[#aname], size)
  else
    if info.ptr_count > 0 then
      aname[#aname+1] = "idx"
      args[#args+1] = "int "..aname[#aname]
    end
    aname[#aname+1] = "src"
    args[#args+1] = _format("%s %s%s", tp, aname[#aname], size)
  end
  local full = _format("%s %s (%s)", ret, nm, _concat(args, ", "))
  return nm, full, aname
end

-- Int setter.
local function _setInt (idx, name)
  -- TODO check sign, range
  return _format('%s = luaL_checkinteger(L, %s);', name, idx)
end

-- Int getter.
local function _getInt (name)
  return _format('lua_pushinteger(L, %s);', name)
end

-- Float setter.
local function _setFloat (idx, name)
  return _format('%s = luaL_checknumber(L, %s);', name, idx)
end

-- Float getter.
local function _getFloat (name)
  return _format('lua_pushnumber(L, %s);', name)
end

-- String setter.
local function _setString (t, idx, name)
  return _format('%s = luaL_checkstring(L, %s);', name, idx)
end

-- String getter.
local function _getString (name)
  return _format('lua_pushstring(L, %s);', name)
end

-- Data setter.
local function _setter(v, goal, index, env)
  if v.ptr_count > 0 and v.Lua ~= 'string' then
    local fname = _cAuxName(v, "to")
    if not env[fname] then aux.LtoPtr(v, env) end
    return _format("%s(L, %s, &(%s));", fname, index, goal)
  elseif #v.arr_size > 0 then
    local fname = _cAuxName(v, "to")
    if not env[fname] then aux.LtoArr(v, env) end
    return _format("%s(L, %s, %s);", fname, index, goal)
  elseif v.Lua == 'int' then
    return _setInt(index, goal)
  elseif v.Lua == 'float' then
    return _setFloat(index, goal)
  elseif v.Lua == 'string' then
    return _setString(v, index, goal)
  elseif v.Lua == 'table' then
    local fname = _cAuxName(v, "to")
    if not env[fname] then aux.LtoStruct(v.C, env) end
    return _format("%s(L, %s, &(%s));", fname, index, goal)
  end
end

-- Data getter.
local function _getter (v, goal, index, env)
  if v.ptr_count > 0 then
    local fname = _cAuxName(v, "from")
    if not env[fname] then aux.LfromPtr(v, env) end
    return _format("%s(L, %s, %s);", fname, index, goal)
  elseif #v.arr_size > 0 and v.Lua ~= "string" then
    local fname = _cAuxName(v, "from")
    if not env[fname] then aux.LfromArr(v, env) end
    return _format("%s(L, %s);", fname, goal)
  elseif v.Lua == "int" then
    return _getInt(goal)
  elseif v.Lua == 'float' then
    return _getFloat(goal)
  elseif v.Lua == "string" then
    return _getString(goal)
  elseif v.Lua == "table" then
    local fname = _cAuxName(v, "from")
    if not env[fname] then aux.LfromStruct(v.C, env) end
    return _format("%s(L, &(%s));", fname, goal)
  end
end

-- Fill struct from Lua table.
aux.LtoStruct = function (str_name, env)
  local struct_var = parser.var(nil, 'table', str_name)
  local fname, fsignature, farg = _cAuxName(struct_var, "to")
  local acc, shift = {}, _shift(1)
  acc[#acc+1] = fsignature
  acc[#acc+1] = "{"
  acc[#acc+1] = shift.._format("luaL_checktype(L, %s, LUA_TTABLE);", farg[2])
  -- set fields
  for i, v in ipairs(env.structs[str_name]) do
    local field = v.var_name
    acc[#acc+1] = shift.._format("// %s %s", v.C, field)
    acc[#acc+1] = shift.._format('lua_getfield(L, %s, "%s");', farg[2], field)
    local p = _format("%s->%s", farg[3], field)
    acc[#acc+1] = shift.._setter(v, p, "-1", env)
    acc[#acc+1] = shift.._format("lua_pop(L, 1);")
  end
  acc[#acc+1] = "}"
  env[fname] = {fsignature, _concat(acc, "\n")}
end

-- Fill Lua table from struct.
aux.LfromStruct = function (str_name, env)
  local struct_var = parser.var(nil, 'table', str_name)
  local fname, fsignature, farg = _cAuxName(struct_var, "from")
  local acc, shift = {}, _shift(1)
  acc[#acc+1] = fsignature
  acc[#acc+1] = "{"
  local fields = env.structs[str_name]
  acc[#acc+1] = shift.._format("lua_createtable(L, 0, %d);", #fields)
  for i, v in ipairs(fields) do
    local field = v.var_name
    acc[#acc+1] = shift.._format("// %s %s", v.C, field)
    local p = _format("%s->%s", farg[2], field)
    acc[#acc+1] = shift.._getter(v, p, nil, env)
    acc[#acc+1] = shift.._format('lua_setfield(L, -2, "%s");', field)
  end
  acc[#acc+1] = "}"
  env[fname] = {fsignature, _concat(acc, "\n")}
end

-- Fill array from Lua table in the loop.
local function _auxLtoArrLoop (sh, ids, lvl, var, nm, env)
  local arr = var.arr_size
  local acc, shift = {}, _shift(sh)
  acc[#acc+1] = shift.._format("luaL_checktype(L, %s, LUA_TTABLE);", ids)
  local len = arr[lvl]
  acc[#acc+1] = shift.._format(
    'if (%d != luaL_len(L, %s)) luaL_error(L, "Expected array of size %d");', 
    len, ids, len)
  local ii = _format("i%d", lvl)
  acc[#acc+1] = shift.._format("// loop %d", lvl)
  acc[#acc+1] = shift.._format("for (lua_Integer %s = 0; %s < %d; %s++) {", ii, ii, len, ii)
  local shift2 = _shift(sh+1)
  acc[#acc+1] = shift2.._format("lua_geti(L, %s, %s+1);", ids, ii)
  local ref = _format("%s[%s]", nm, ii)
  if lvl == #arr then
    local tmp = parser.var(var.var_name, var.Lua, var.C)
    acc[#acc+1] = shift2.._setter(tmp, ref, "-1", env)
  else
    acc[#acc+1] = _auxLtoArrLoop(sh+1, "-1", lvl+1, var, ref, env)
  end
  acc[#acc+1] = shift2.._format("lua_pop(L, 1);")
  acc[#acc+1] = shift.."}"
  return _concat(acc, "\n")
end

-- Fill array from Lua table.
aux.LtoArr = function (array, env)
  local fname, fsignature, fargs = _cAuxName(array, "to")
  local acc = {fsignature, "{",
    _auxLtoArrLoop(1, fargs[2], 1, array, fargs[3], env), 
    "}"}
  env[fname] = {fsignature, _concat(acc, "\n")}
end

-- Fill Lua table from array in the loop.
local function _auxLfromArrLoop (sh, lvl, var, nm, env)
  local arr = var.arr_size
  local acc, shift = {}, _shift(sh)
  local len, ii = arr[lvl], _format("i%d", lvl)
  acc[#acc+1] = shift.._format("lua_createtable(L, %d, 0);", len)
  acc[#acc+1] = shift.._format("for (lua_Integer %s = 0; %s < %d; %s++) {", ii, ii, len, ii)
  local shift2 = _shift(sh+1)
  local ref = _format("%s[%s]", nm, ii)
  if lvl == #arr then
    local tmp = parser.var(var.var_name, var.Lua, var.C)
    acc[#acc+1] = shift2.._getter(tmp, ref, nil, env)
  else
    acc[#acc+1] = _auxLfromArrLoop(sh+1, lvl+1, var, ref, env)
  end
  acc[#acc+1] = shift2.._format("lua_seti(L, -2, %s+1);", ii)
  acc[#acc+1] = shift.."}"
  return _concat(acc, "\n")
end

-- Fill Lua table from array.
aux.LfromArr = function (array, env)
  local fname, fsignature, fargs = _cAuxName(array, "from")
  local acc = {fsignature, "{",
    _auxLfromArrLoop(1, 1, array, fargs[2], env), 
    "}"}
  env[fname] = {fsignature, _concat(acc, "\n")}
end

-- Data allocation function.
aux.tblAlloc = {
-- name
"l_tbl_alloc",
{
-- signature
"void* l_tbl_alloc (lua_State* L, int* idx, size_t size)" ,
-- definition
[[void* l_tbl_alloc (lua_State* L, int* idx, size_t size)
{
  if (*idx == 0) {
    // push empty table 
    lua_newtable(L);
    *idx = lua_gettop(L);
  }
  lua_Integer n = luaL_len(L, *idx);
  void* p = lua_newuserdata(L, size);
  if (!p) luaL_error(L, "Unable to allocate memory");
  // put allocated data to table
  lua_seti(L, *idx, n+1);
  return p;
}]]
},
-- variable name
"mem"}

-- Fill dynamic array from Lua table in the loop.
local function _auxLtoDynArr (sh, ids, lvl, var, nm, env)
  local acc, shift = {}, _shift(sh)
  local len, data = _format("l%d", lvl), _format("d%d", lvl)
  acc[#acc+1] = shift.._format("%s%s %s = NULL;", var.C, _rep("*", var.ptr_count-lvl+1), data)
  acc[#acc+1] = shift.._format("luaL_checktype(L, %s, LUA_TTABLE);", ids)
  acc[#acc+1] = shift.._format("lua_Integer %s = luaL_len(L, %s);", len, ids)
  if not env[aux.tblAlloc[1]] then
    env[aux.tblAlloc[1]] = aux.tblAlloc[2]
  end
  acc[#acc+1] = shift.._format("if (%s > 0) {", len)
  local shift1 = _shift(sh+1)
  acc[#acc+1] = shift1.._format("%s = %s(L, &%s, %s*sizeof(%s%s));", 
    data, aux.tblAlloc[1], aux.tblAlloc[3], len, var.C, _rep("*", var.ptr_count-lvl))
  local ii = _format("i%d", lvl)
  acc[#acc+1] = shift1.._format("for (lua_Integer %s = 0; %s < %s; %s++) {", ii, ii, len, ii)
  local shift2 = _shift(sh+2)
  acc[#acc+1] = shift2.._format("lua_geti(L, %s, %s+1);", ids, ii)
  local ref = _format("%s[%s]", data, ii)
  if lvl == var.ptr_count then
    local tmp = parser.var(var.var_name, var.Lua, var.C)
    acc[#acc+1] = shift2.._setter(tmp, ref, "-1", env)
  else
    acc[#acc+1] = _auxLtoDynArr (sh+2, "-1", lvl+1, var, ref, env)
  end
  acc[#acc+1] = shift2.."lua_pop(L, 1);"
  acc[#acc+1] = shift1.."}"
  acc[#acc+1] = shift.."} else {"
  acc[#acc+1] = shift1..'luaL_error(L, "Empty array");'
  acc[#acc+1] = shift.."}"
  acc[#acc+1] = shift.._format("%s = %s;", nm, data)
  return _concat(acc, "\n")
end

-- Fill dynamic array from Lua table.
aux.LtoPtr = function (array, env)
  local fname, fsignature, fargs = _cAuxName(array, "to")
  local acc, shift = {}, _shift(1)
  acc[#acc+1] = fsignature
  acc[#acc+1] = "{"
  acc[#acc+1] = shift.._format("int %s = 0;", aux.tblAlloc[3])
  acc[#acc+1] = _auxLtoDynArr(1, fargs[2], 1, array, "*"..fargs[3], env)
  acc[#acc+1] = body
  acc[#acc+1] = "}"
  env[fname] = {fsignature, _concat(acc, "\n")}
end

-- Fill Lua table from dynamic array in the loop.
local function _auxLfromDynArr (sh, ids, lvl, var, nm, env)
  local acc, shift = {}, _shift(sh)
  local len, data = _format("l%d", lvl), _format("d%d", lvl)
  acc[#acc+1] = shift.._format("lua_Integer %s = luaL_len(L, %s);", len, ids)
  local ii = _format("i%d", lvl)
  acc[#acc+1] = shift.._format("// loop %d", lvl)
  acc[#acc+1] = shift.._format("for (lua_Integer %s = 0; %s < %s; %s++) {", ii, ii, len, ii)
  local shift1 = _shift(sh+1)
  local ref = _format("%s[%s]", nm, ii)
  if lvl == var.ptr_count then
    local tmp = parser.var(var.var_name, var.Lua, var.C)
    acc[#acc+1] = shift1.._getter(tmp, ref, nil, env)
  else
    acc[#acc+1] = _auxLfromDynArr(sh+1, "-1", lvl+1, var, ref, env)
  end
  acc[#acc+1] = shift1.._format("lua_seti(L, -2, %s+1);", ii)
  acc[#acc+1] = shift.."}"
  return _concat(acc, "\n")
end

-- Fill Lua table from dynamic array.
aux.LfromPtr = function (array, env)
  local fname, fsignature, fargs = _cAuxName(array, "from")
  local acc, shift = {}, _shift(1)
  acc[#acc+1] = fsignature
  acc[#acc+1] = "{"
  acc[#acc+1] = shift.."// copy input table"
  acc[#acc+1] = shift.._format("lua_pushvalue(L, %s);", fargs[2])
  acc[#acc+1] = _auxLfromDynArr(1, "-1", 1, array, fargs[3], env)
  acc[#acc+1] = "}"
  env[fname] = {fsignature, _concat(acc, "\n")}
end

-- Declare function arguments.
local function _declareArgs (func, args, attr, env)
  local acc, shift = {}, _shift(1)
  acc[#acc+1] = shift.."// declare varialbes"
  for _, arg in ipairs(args) do
    local t = {arg.C}
    if arg.ptr_count > 0 then
      t[#t+1] = _rep("*", arg.ptr_count)
    end
    t[#t+1] = " "..arg.var_name
    if #arg.arr_size > 0 then
      t[#t+1] = _arr2str(arg.arr_size)
    end
    t[#t+1] = ";"
    acc[#acc+1] = shift.._concat(t)
  end
  if func.ptr_count > 0 then
    error("Dynamic array as a return type is not implemented")
  end
  if func.C ~= "void" then
    -- declare
    local nm = _fnResult(func)
    local tp = func.C
    acc[#acc+1] = shift.._format("%s %s;", tp, nm)
  end
  return _concat(acc, '\n')
end

-- Fill C arguments from Lua arguments.
local function _LtoArgs (args, attr, env)
  local acc, shift = {}, _shift(1)
  local n = 1
  acc[#acc+1] = shift.."// init arguments"
  for _, arg in ipairs(args) do
    if not attr.out[arg.var_name] then
      acc[#acc+1] = shift.._setter(arg, arg.var_name, tostring(n), env)
      n = n + 1
    end
  end
  return _concat(acc, "\n"), n-1
end

-- Function call.
local function _callFunction (func, args, attr, env)
  local acc, shift = {}, _shift(1)
  local t = {}
  for i, arg in ipairs(args) do
    t[i] = arg.var_name
  end
  local call = _format("%s(%s);", func.var_name, _concat(t, ", "))
  if func.C ~= "void" then
    call = _format("%s = %s", _fnResult(func), call)
  end
  acc[#acc+1] = shift.."// call function"
  acc[#acc+1] = shift..call
  return _concat(acc, "\n")
end

-- Fill Lua outputs.
local function _LfromArgs (func, args, attr, env)
  local acc, shift = {}, _shift(1)
  acc[#acc+1] = shift.."// return values"
  local n = 0
  if func.C ~= "void" then
    local tmp = parser.var(_fnResult(func), func.Lua, func.C, func.ptr_count, func.arr_size)
    acc[#acc+1] = shift.._getter(tmp, tmp.var_name, nil, env)
    n = n + 1
  end
  local m = 0  -- stack position
  for _, arg in ipairs(args) do
    if not attr.out[arg.var_name] then m = m+1 end
    if attr.out[arg.var_name] or attr.inout[arg.var_name] then
      if arg.ptr_count > 0 and not attr.inout[arg.var_name] then
        error("Dynamic array allowd only for input or inout arguments, found for "..arg.var_name)
      end
      acc[#acc+1] = shift.._getter(arg, arg.var_name, tostring(m), env)
      n = n + 1
    end
  end
  return _concat(acc, "\n"), n
end

-- Generator class
local generator = {}

-- Generate function text.
generator.makeFunction = function (func, farg, fattr, env)
  local name = fattr.name or func.var_name
  local cname = 'l_'..name
  local acc = {}
  local nin, nout = 0, 0
  acc[#acc+1] = _format('static int %s (lua_State* L)', cname)
  acc[#acc+1] = '{'
  acc[#acc+1] = _declareArgs(func, farg, fattr, env)
  acc[#acc+1], nin = _LtoArgs(farg, fattr, env)
  acc[#acc+1] = _callFunction(func, farg, fattr, env)
  acc[#acc+1], nout = _LfromArgs(func, farg, fattr, env)
  acc[#acc+1] = _shift(1).._format("return %d;", nout)
  acc[#acc+1] = '}'
  return {Lua=name, C=cname, body=_concat(acc, '\n')}
end

-- Generate file text.
generator.makeLibFile = function (attr, fn_list, struct)
  local env, translate = {}, {}
  env.structs = struct
  -- generate functions
  for _, param in ipairs(fn_list) do
    translate[#translate+1] = generator.makeFunction(param[1], param[2], param[3], env)
  end
  local txt = {}
  local libname = attr.name or attr.fname
  txt[#txt+1] = _format(HEAD, libname, attr.description or '', attr.fname_h)
  -- aux functions declaration
  for k, v in pairs(env) do
    if string.find(k, "^l_") then
      txt[#txt+1] = v[1]..";"
    end
  end
  -- aux functions definition
  for k, v in pairs(env) do
    if string.find(k, "^l_") then
      txt[#txt+1] = ""
      txt[#txt+1] = v[2]
    end
  end
  -- main functions
  for _, tr in ipairs(translate) do
    txt[#txt+1] = ""
    txt[#txt+1] = tr.body
  end
  -- function registration
  txt[#txt+1] = '\n// Register functions'
  txt[#txt+1] = _format('static const struct luaL_Reg %s[] = {', libname)
  local shift = _shift(1)
  for _, tr in ipairs(translate) do
    txt[#txt+1] = shift.._format('{"%s", %s},', tr.Lua, tr.C)
  end
  txt[#txt+1] = shift..'{NULL, NULL}\n};\n'
  txt[#txt+1] = _format(TALE, libname, libname)

  -- save file
  local fname = _format('lua%s.c', attr.fname)
  local f = io.open(fname, 'w')
  f:write(_concat(txt, '\n'))
  f:close()
  return fname
end

generator.compile = function (attr, names)
  local t = {attr.compiler}
  table.insert(t, attr.include)
  for _, nm in ipairs(names) do t[#t+1] = nm end
  if attr.name then
    t[#t+1] = "-o"
    t[#t+1] = attr.name .. '.so'
  end
  table.insert(t, attr.lib)
  table.insert(t, attr.flags)
  local cmd = table.concat(t, " ")
  print(cmd)
  local ok, res = os.execute(cmd)
end

generator.makeBin = function (src)
  local attr, fn_list, struct = parser.parse(src[1])
  local cname = generator.makeLibFile(attr, fn_list, struct)
  local files = {cname}
  for _, nm in ipairs(src) do files[#files+1] = nm end
  generator.compile(attr, files)
end

return generator

